unbind C-b
set-option -g prefix C-t
bind C-t send-prefix

set-option -g buffer-limit 20
set-option -g history-limit 5000
set-window-option -g mode-keys emacs

# https://qiita.com/puriso/items/9cec04eaba47a9d563ea
set-option -g default-shell "/usr/local/bin/fish"
set -g default-command "/usr/local/bin/fish"